"""W3: share_attach

Revision ID: 9f246cb32d6e
Revises: b3fce6fbe4b6
Create Date: 2026-10-10 13:29:13.577726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f246cb32d6e'
down_revision = 'b3fce6fbe4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_attach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("target_type IN ('article', 'page')", name='ck_share_attach_target_type'),
    sa.ForeignKeyConstraint(['share_id'], ['cloud_share.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_attach', schema=None) as batch_op:
        batch_op.create_index('idx_share_attach_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_attach_share_id'), ['share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_attach_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_attach', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_attach_target_id'))
        batch_op.drop_index(batch_op.f('ix_share_attach_share_id'))
        batch_op.drop_index('idx_share_attach_target')

    op.drop_table('share_attach')
    # ### end Alembic commands ###
