"""W3: file_usage, audit_log, archive settings, article.archived_at

Revision ID: bec349bf7b84
Revises: def34305bcda
Create Date: 2026-10-06 23:36:18.804480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec349bf7b84'
down_revision = 'def34305bcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('file_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['cloud_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'entity_type', 'entity_id', name='uq_file_usage')
    )
    with op.batch_alter_table('file_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_file_usage_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_usage_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_usage_file_id'), ['file_id'], unique=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_article_archived_at'), ['archived_at'], unique=False)

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_after_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('archive_retention_days', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('archive_retention_days')
        batch_op.drop_column('archive_after_days')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_archived_at'))
        batch_op.drop_column('archived_at')

    with op.batch_alter_table('file_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_usage_file_id'))
        batch_op.drop_index(batch_op.f('ix_file_usage_entity_id'))
        batch_op.drop_index('ix_file_usage_entity')
        batch_op.drop_index(batch_op.f('ix_file_usage_created_at'))

    op.drop_table('file_usage')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
